"""Domain schemas, scoring rules, and validation utilities."""

from srs_signal.domain.admission import (
    AdmittedReviewedAuditHandle,
    AdmittedValidatedAuditHandle,
    AdmissionError,
    admit_reviewed_audit,
    admit_validated_audit,
    create_reviewed_audit,
)

from srs_signal.domain.dimensions import (
    CANONICAL_DIMENSION_IDS,
    CANONICAL_DIMENSION_NAMES,
)
from srs_signal.domain.enums import (
    AnalysisProviderType,
    AnalysisStatus,
    ConfidenceLevel,
    DimensionId,
    DimensionStatus,
    EvidenceMatchMethod,
    InstitutionType,
    ReviewAction,
    ReviewerStatus,
    ReviewStatus,
)
from srs_signal.domain.schemas import (
    AggregateSignal,
    DecisionMetadata,
    DimensionAggregate,
    DimensionFinding,
    EvidenceValidatedDimensionFinding,
    EvidenceQuote,
    HumanReview,
    InstitutionTypeCountEntry,
    ProvisionalAuditResult,
    RecurrencePattern,
    ReviewedAuditResult,
    ReviewedDimensionFinding,
    ScoreCountEntry,
    StatusCountEntry,
    ValidatedAuditResult,
)

__all__ = [
    "AdmittedReviewedAuditHandle",
    "AdmittedValidatedAuditHandle",
    "AdmissionError",
    "AggregateSignal",
    "AnalysisProviderType",
    "AnalysisStatus",
    "CANONICAL_DIMENSION_IDS",
    "CANONICAL_DIMENSION_NAMES",
    "ConfidenceLevel",
    "DecisionMetadata",
    "DimensionAggregate",
    "DimensionFinding",
    "DimensionId",
    "DimensionStatus",
    "EvidenceValidatedDimensionFinding",
    "EvidenceMatchMethod",
    "EvidenceQuote",
    "HumanReview",
    "InstitutionType",
    "InstitutionTypeCountEntry",
    "ProvisionalAuditResult",
    "RecurrencePattern",
    "ReviewAction",
    "ReviewedAuditResult",
    "ReviewedDimensionFinding",
    "ReviewerStatus",
    "ReviewStatus",
    "ScoreCountEntry",
    "StatusCountEntry",
    "ValidatedAuditResult",
    "admit_reviewed_audit",
    "admit_validated_audit",
    "create_reviewed_audit",
]
